name: Release
on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Publish to npm
        run: yarn publish --new-version `echo '${{ github.ref }}' | cut -d 'v' -f 2`
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
